apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      NodePort: 30001
