version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"  # Enclosed password in quotes for consistency
      MYSQL_DATABASE: "db_task"         # Enclosed database name in quotes
      MYSQL_USER: "app-user"            # Enclosed username in quotes
      MYSQL_PASSWORD: "123456789"       # Enclosed password in quotes

  task-backend:
    image: medaminebens/task-backend-image:latest
    restart: always
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/db_task
      SPRING_DATASOURCE_USERNAME: "app-user"            # Enclosed username in quotes
      SPRING_DATASOURCE_PASSWORD: "123456789"          # Enclosed password in quotes
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"  # Enclosed driver class in quotes
    depends_on:
      - mysql

  task-frontend:
    image: medaminebens/task-frontend-image:latest
    restart: always
    environment:
      VITE_TASK_BACKEND_API_URL: "http://localhost:8088/api"  # Updated backend URL to include the port
    ports:
      - "3000:3000"
    depends_on:
      - task-backend

volumes:
  mysql-data: