version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes: 
     - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: app-user
      MYSQL_DATABASE: db_task
      MYSQL_PASSWORD: 123456789

  task-backend:
    image: task-backend
    restart: always
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/db_task
      SPRING_DATASOURCE_USERNAME: app-user
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - mysql

  task-frontend:
    image: task-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - task-backend
volumes:
  mysql-data:
