apiVersion: v1
kind: Service
metadata:
  name: react-js-service
spec:
  selector:
    app: front-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 4000
